# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - kyiwasak-demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_b972c30ea76d4c31b2e1a473a0d467d5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c3c09854c99e436296ea31bf3852c6be }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_b972c30ea76d4c31b2e1a473a0d467d5 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'kyiwasak-demo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_969ba3e30c10460ca1d0f6fe8acb426a }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_b972c30ea76d4c31b2e1a473a0d467d5 }}/appsvc/staticsite:${{ github.sha }}'